---
- hosts: OBBservers
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: make sure firewalld is installed
    yum:
     name: firewalld
     state: latest
     update_cache: yes

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
